### ISSUE TITLE
How many activities are missing from the datastore?

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Datastore#185]
As part of my ongoing work to determine where activities are missing from the datastore, I've extracted a list of all the `iati-identifier`s in a [full XML download](http://datastore.iatistandard.org/docs/api/#getting-all-the-results-at-once) from the datastore, and compared it against the list of all identifiers generated by the dashboard.

In the datastore, but not the dashboard: 489 ([json](http://iati.bjwebb.co.uk/datastore-dashboard-identifiers/not_in_dashboard.json))
In the dashboard, but not the datastore: 17125 ([json](http://iati.bjwebb.co.uk/datastore-dashboard-identifiers/not_in_datastore.json))

Currently the majority of identifiers missing from the dashboard (15173) are Swedish, and likely due to their large XML file failing import https://github.com/IATI/iati-datastore/issues/182

The aspiration is for this to be a nightly process (and possibly part of the dashboard), but it isn't yet.

The full lists of all iati-identifiers for the [datastore](http://iati.bjwebb.co.uk/datastore-dashboard-identifiers/datastore_iati_identifiers.json) and the [dashboard](http://dashboard.iatistandard.org/stats/current/aggregated/iati_identifiers.json) are also availible. (note these are large ~20MB):

**Comment by dalepotter** [comment]
To note, IATI-Website-Tests now makes various global consistency checks, including a check for number of activities in the Datastore vs. the recorded number in the Dashboard.

Relevant code is here: https://github.com/IATI/IATI-Website-Tests/blob/ec36cbdaca1a8c75728baff432fff97b22c2f8f6/tests/test_global_consistency.py#L133-L142 although note this is marked as `xfail` for the time being whilst enquiries are ongoing to investigate current inconsistencies.
