### ISSUE TITLE
Logging issues / Canadian activities have disappeared from IATI Datastore

### ISSUE THREAD

**Issue by markbrough** [IATI/IATI-Datastore#211]
http://datastore.iatistandard.org/api/1/access/activity?reporting-org=CA-3

Could potentially be multiple activities with the same iati-identifier, as there are segmented and non-segmented files here?
http://iatiregistry.org/publisher/dfatd-maecd

But there's no error to that effect shown in the logs:
http://datastore.iatistandard.org/api/1/about/dataset/dfatd-maecd-act
http://datastore.iatistandard.org/api/1/error/dataset/dfatd-maecd-act
http://datastore.iatistandard.org/api/1/about/dataset/dfatd-maecd-act_2_3
http://datastore.iatistandard.org/api/1/error/dataset/dfatd-maecd-act_2_3

I guess the answer is that there should be some more obvious logging of what the error was here?

**Comment by markbrough** [comment]
Still appears to be no data returned - looks like the issue is now something else, to do with integrity errors with empty strings for organisation identifiers (which I presume will be having wider effects than just for Canada?):

http://datastore.iatistandard.org/api/1/error/dataset/dfatd-maecd-act_2_3

> IntegrityError: (IntegrityError) duplicate key value violates unique constraint \\\"organisation_ref_name_type_key\\\"
> DETAIL: Key (ref, name, type)=(, ALNAP - Active Learning Network for Accountability and Performance in Humanitarian Action, 0) already exists.
> 'INSERT INTO organisation (ref, name, type) VALUES (%(ref)s, %(name)s, %(type)s) RETURNING organisation.id' {'ref': u'', 'type': u'0', 'name': u'ALNAP - Active Learning Network for Accountability and Performance in Humanitarian Action'}\n\"}

**Comment by Bjwebb** [comment]
Sorry, haven't had much chance to look into this. I can reproduce, and it looks like it's a problem with how the [uniqueness cache](https://github.com/IATI/iati-datastore/blob/master/iati_datastore/iatilib/model.py#L39) interacts with codes that aren't on the codelist (as codes not on the codelist are currently created as unique objects even if they have the same value).

**Comment by YohannaLoucheur** [comment]
Was this perhaps solved last week when we removed the trailing whitespaces (or whatever they're called)?

**Comment by dalepotter** [comment]
The current datastore output for reporting-org `CA-3` is showing 3801 activities: http://datastore.iatistandard.org/api/1/access/activity?reporting-org=CA-3

Given that yesterday's version of the Dashboard is showing 3802 activities for [Canada - Global Affairs Canada | Affaires mondiales Canada](http://dashboard.iatistandard.org/publisher/gac-amc.html) (i.e. reporting-org `CA-3`), I am going to mark this issue as closed.
