### ISSUE TITLE
Make the human query builder part of this codebase.

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Datastore#212]
The code to create a query string for the datastore is currently from code in this repository:
https://github.com/IATI/IATI-Query-Builder

We should integrate this into the datastore code itself - although as a standalone module perhaps.

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), it is currently intended that these products are maintained separately since their functionality is separate beyond the shared API.
