### ISSUE TITLE
CSV output requests from the registry could be handled by the datastore

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Datastore#213]
There has long been talk that the service currently provided at:
http://tools.aidinfolabs.org/csv

that transforms IATI XML into csv, could/should be provided by the datastore.

This would mean 
- reconfiguring the 'CSV' links out from the registry to point elsewhere
- making the datastore handle the request in such a way that humans can understand their subsequent choices

This in turn may involve the ticket: https://github.com/IATI/iati-datastore/issues/212

**Comment by hayfield** [comment]
This functionality is planned to be provided within the Python Library.

IATI/AidInfoLabs-CSV-Downloader#3
