### ISSUE TITLE
API output doesn't give the right count

### ISSUE THREAD

**Issue by anjesh** [IATI/iati-datastore#243]
UNDP activities API shows 8708 as total number of activities 
http://datastore.iatistandard.org/api/1/access/activity.xml?reporting-org=XM-DAC-41114&limit=1
![image](https://cloud.githubusercontent.com/assets/120488/15664822/a821312a-2726-11e6-9838-65cca0027752.png)

where as D-portal shows 9279
http://d-portal.org/ctrack.html?&publisher=XM-DAC-41114#view=publisher

![image](https://cloud.githubusercontent.com/assets/120488/15664833/baaf5dc6-2726-11e6-8804-3fc7170b1654.png)

The latter is the correct one, and is also reflected in the dashboard.http://dashboard.iatistandard.org/stats/current/aggregated-publisher/undp/

Is there any other way to call the API to get the correct numbers?

**Comment by dalepotter** [comment]
Hi Anjesh, Thanks for flagging this. There could well be issues with results from API calls to the Datastore - this probably relates to issues we've been having for some time on activities not correctly importing to the datastore.

Unfortunately there has been limited time to get to the bottom of such issues on account of a big push in recent months towards various fixes and methodology changes for the work on the Dashboard and the Global Partnership transparency indicator and associated coverage scoring.

There are a number of other runtime datastore runtime issues which we hope to get this resolved when time allows.

**Comment by dalepotter** [comment]
Just as an update to this one, we're re-importing the full set of IATI data from scratch on a development version of the datastore which may resolve the problem. I've set this off earlier today, and we'll be able to take a look on Monday to see if this helps. Will update further in due course.

Many thanks in the meantime for your patience.

**Comment by anjesh** [comment]
Thanks Dale. It would be great if this works soon. In the meantime, we have started pulling data directly from the registry for few agencies.

**Comment by dalepotter** [comment]
Hi @anjesh just to say that the re-import of the datastore from scratch has completed and is now showing an increased count for the [API call](http://datastore.iatistandard.org/api/1/access/activity.xml?reporting-org=XM-DAC-41114&limit=1) that you first referenced:

```
<result xmlns:iati-extra="http://datastore.iatistandard.org/ns">
<ok>True</ok>
<iati-activities generated-datetime="2016-06-06T18:38:31.217201">
  <query>
    <total-count>9279</total-count>
    <start>0</start>
    <limit>1</limit>
  </query>
```

As such I'll mark this issue as closed for the time being. It's probably worth continuing to pull data from the registry for new applications - we don't have a huge amount of time to devote to the upkeep of the datastore so can't guarantee this sort of thing won't happen in future.

**Comment by anjesh** [comment]
Thanks Dale.
