### ISSUE TITLE
I can output csv files with custom filenames

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Datastore#250]
The csv routes aren’t sufficiently strict about the bit between the final segment of the route and the ‘csv’ ending E.g. both /api/1/access/budget.csv and /api/1/access/budgets.csv work:

 * http://datastore.iatistandard.org/api/1/access/budget.csv
 * http://datastore.iatistandard.org/api/1/access/budgets.csv

In fact, the following custom filename hack also works:

http://datastore.iatistandard.org/api/1/access/budgettt.Hey_look.A_custom_filename.csv

Kind of cool. But probably worth fixing. [I suspect checking the value of format rather than `request.path.endswith` would do the trick.](https://github.com/IATI/IATI-Datastore/blob/30177c55/iati_datastore/iatilib/frontend/api1.py#L226)

**Comment by dalepotter** [comment]
Issue reopened as this is the subject of pull request into the production version of the code: https://github.com/IATI/IATI-Datastore/pull/258

**Comment by andylolz** [comment]
Closing because this was fixed by #251 (although the related tests in #263 – requested by @hayfield in #258, and originally the blocker for pushing this live – have not been merged).
