### ISSUE TITLE
Vast majority of errors are `SSLError`s…

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Datastore#261]
…and the vast majority of these (almost 900 at present) are for datasets on https://aidstream.org

I’ve [opened an issue on the aidstream repo](https://github.com/younginnovations/aidstream/issues/93) but I wonder if this is worth addressing here too.

**Comment by hayfield** [comment]
As mentioned in https://github.com/younginnovations/aidstream/issues/93, this seems to be a problem with Aidstream's certificate chain rather than the Datastore.

**Comment by andylolz** [comment]
Well, so… `requests` rejects this is because `openssl` is being very strict here (more so than any browser, meaning it’s maybe not obvious to a user/publisher what the problem is.)

I think this also has something in common with #254: While this issue is in fact upstream, it does negatively affect the output of the datastore, and it would be possible to take steps here to ameliorate that… Obviously I’m not entirely convinced by this argument given my comments in #254! But taken together with the first point about OpenSSL being strict, it’s compelling.)

**Comment by andylolz** [comment]
The issue with AidStream is fixed now (in fact it was fixed very quickly! Thanks @sachit-singh!) and this ticket doesn’t really have a clear ask.

So I’ll close this issue and create two new ones:

 1. Don’t validate SSL certs when fetching data (#264)
 2. Make the datastore API available over SSL (#265)
