### ISSUE TITLE
Last fetch date was 7 days ago… How often does the crawler run?

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Datastore#271]
[Documentation suggests the datastore crawler runs daily](https://github.com/IATI/IATI-Datastore/blob/master/docs/user-guide/how-is-the-data-updated.rst#updates)… But checking `last_fetch` date on all datasets, the most recent update was ~~nearly~~ over a week ago.

**Comment by andylolz** [comment]
Hmm this still looks broken…

Looks like running `iati crawler status` on the datastore server might provide some clues?
https://github.com/IATI/IATI-Datastore/blob/5b871aa3/iati_datastore/iatilib/crawler.py#L422-L423

**Comment by andylolz** [comment]
@andylolz wrote:
> But checking `last_fetch` date on all datasets

Here’s the code (and its output) I used to check that:
https://gist.github.com/andylolz/d991656c853d012f85b1468354c36a8e

**Comment by andylolz** [comment]
I’ve just tried debugging this, and it looks like the first URL that the crawler hits is 404ing:
https://www.iatiregistry.org//api/action/package_list

Removing the double-slash fixes the problem:
https://www.iatiregistry.org/api/action/package_list

I’ve fixed the CKAN API base URL in PR #272.

**Comment by andylolz** [comment]
The crawler is working again 🎉 🎉 🎉

**Comment by stevieflow** [comment]
thanks @andylolz --- I was looking for FAO data , but not there.  Maybe it will kick in with the new crawl...

**Comment by andylolz** [comment]
@stevieflow wrote:
> I was looking for FAO data , but not there. Maybe it will kick in with the new crawl...

I don’t think so, no :( the crawler ran last night. It looks like the data isn’t being parsing due to the 304 server response:
http://datastore.iatistandard.org/api/1/about/dataset/fao-activity

…so I suspect it’s the same issue as #268.

**Comment by andylolz** [comment]
Crawler appears to be broken again.

**Comment by hayfield** [comment]
I've restarted the server and it seems to be updating again - by the looks of it, the crawler is set to run on reboot, and if it stops running then that's it.

Have also added an action to create a test that automatically checks that the Datastore has updated its contained data recently (like the equivalent test for the Dashboard).

**Comment by dalepotter** [comment]
I was thinking about this last night and remembered that issue #230 exists.

It might be that the worker is only set to run at reboot because it is designed to be constantly running, even after it finishes parsing queued datasets.

**Comment by andylolz** [comment]
The worker (`iati queue background`) should constantly run. The crawler (`iati crawl update`) should run every 24 hours. Presumably there’s a cronjob for that, since that seems to be happening.

It looooooks like everything is working normally now… When I run locally, the `last_fetched` data looks reasonably similar.

**Comment by allthatilk** [comment]
Hi everybody! 

So after some digging and things we've determined that `last_fetch` and `last_successful_fetch` don't update for every dataset every time the crawler runs. They only update based on changes to the IATI registry. If no changes have been [detected by the registry](https://github.com/IATI/IATI-Datastore/blob/852ec9a33c0f44f674fb6cdcd6cf7c9fe4ac9e8e/iati_datastore/iatilib/crawler.py#L41-L54), the crawler will skip these datasets. So excluding problems with the registry and the Datastore going down, the crawler should run, as scheduled, every day.

**Comment by andylolz** [comment]
> So after some digging and things we've determined that `last_fetch` and `last_successful_fetch` don't update for every dataset every time the crawler runs.

That is true, although it’s not how it’s documented to work:
http://datastore.iatistandard.org/docs/api/error/#general-data

…so there’s an issue there.

This issue was about the fact that *none* of the `last_fetch` dates were recent, which strongly suggested that something was awry! The bug in question was resolved in #272, and then some mysterious problem was resolved by restarting.

I’m still not really confident that this does, in fact, run nightly, but it’s not terribly easy to ascertain whether everything is fine. It would be wonderful if http://datastore.iatistandard.org/api/1/about provided more reliable data – rather than a hardcoded `ok: True` and `status: healthy`:

https://github.com/IATI/IATI-Datastore/blob/852ec9a33c0f44f674fb6cdcd6cf7c9fe4ac9e8e/iati_datastore/iatilib/frontend/api1.py#L34-L39

**Comment by andylolz** [comment]
> At that time there were some problems with the registry that would have made the crawler think no updates had been made for a while.

Good to have this update! I don’t think I had any idea about that.

> The crawler does run nightly regardless.

My point here is: I have no way of verifying that. So it’s not that I don’t trust you… But for piece of mind, a route that tells me what happened and when would help set my mind at ease. I’ll create an issue for that.

> Other issues found in the process of looking at this one (such as docs) should have their own issue.

In fact, I was wrong about http://datastore.iatistandard.org/docs/api/error/#general-data – the documentation is accurate on this.

**Comment by markbrough** [comment]
Why was this issue closed? The Datastore does not appear to be running nightly. See #268

**Comment by hayfield** [comment]
> Why was this issue closed?

[As noted by](https://github.com/IATI/IATI-Datastore/issues/271#issuecomment-332538427) @allthatilk, the Datastore is working as expected.

**Comment by andylolz** [comment]
> [As noted by](https://github.com/IATI/IATI-Datastore/issues/271#issuecomment-332538427) @allthatilk, the Datastore is working as expected.

@allthatilk’s comment was:

> So excluding problems with the registry and the Datastore going down, the crawler should run, as scheduled, every day.

But this certainly doesn’t mean the Datastore is working as expected. Indeed, #268 is a clear example of the Datastore not working as expected.
