### ISSUE TITLE
Typos in the API documentation

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Datastore#274]
> start-date
> 
> Returns activities where the date with in @activity-date element (with type equivalent to start-planned or start-actual) of an activity is less or greater than your specified query.
> 
> This API element has two sub-elements: **to return activities less than your specified date**, use start-date__lt, or **to return activities less than your specified date** use start-date__gt
> 
> Parameters:
> @start-date: ISO format date (YYYY-MM-DD).
> Example API calls:
> /api/1/access/activity.xml?start-date__lt=2015-01-01 /api/1/access/activity.xml?start-date__gt=2015-01-01
> end-date
> 
> Returns activities where the @activity-date element (with type equivalent to end-planned or end-actual) of an activity is less or greater than your specified query.
> 
> This API element has two sub-elements: **to return activities less than your specified date**, use end-date__lt, or **to return activities less than your specified date** use end-date__gt
> 
> Parameters:
> @end-date: ISO format date (YYYY-MM-DD).
> Example API call:
> /api/1/access/activity.xml?end-date__lt=2015-01-01 /api/1/access/activity.xml?end-date__gt=2015-01-01
> last-change
> 
> Returns activities where the observed last change the of an activity is less or greater than your specified query.
> 
> This differs from the last-updated-datetime. filter, as the last-date filter is based on when the Datastore process observed a change in data. The last-updated-datetime. filter returns data based on the @last-updated-datetime attribute contained within the data itself.
> 
> This API element has two sub-elements: **to return activities less than your specified date**, use last-change__lt, or **to return activities less than your specified date** use last-change__gt
> 
> Parameters:
> @last-change: ISO format date (YYYY-MM-DD).
> Example API calls:
> /api/1/access/activity.xml?last-change__lt=2009-01-01 /api/1/access/activity.xml?last-change__gt=2009-01-01
> last-updated-datetime
> 
> Returns activities where the @last-updated-datetime attribute of an activity is less or greater than your specified query.
> 
> This differs from the last-change. filter, as the last-updated-datetime filter returns data based on the @last-updated-datetime attribute contained within the data itself. The last-change. filter is based on when the Datastore process observed a change in data.
> 
> This API element has two sub-elements: **to return activities less than your specified date**, use last-updated-datetime__lt, or **to return activities less than your specified date** use last-updated-datetime__gt
> 
> Parameters:
> @last-updated-datetime: ISO format date (YYYY-MM-DD).
> Example API calls:
> /api/1/access/activity.xml?last-updated-datetime__lt=2015-01-01 /api/1/access/activity.xml?last-updated-datetime__gt=2010-01-01

In every one of these date-related sections the paragraph about sub-elements refers to both sub-elements as returning less than the specified date so it's not obvious which sub-element should be used.

**Comment by andylolz** [comment]
I suppose “less than” should say “earlier than”, or (even better) “before”.

**Comment by andylolz** [comment]
Most of these were fixed in https://github.com/IATI/IATI-Guidance/commit/4f511846. Here’s a PR for the remaining one: https://github.com/IATI/IATI-Guidance/pull/296
