### ISSUE TITLE
Bug with last_updated_datetime with API endpoint

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Datastore#276]
The last_updated_datetime value seems to be returning a strange string date when running this query
`http://datastore.iatistandard.org/api/1/access/activity.xml?limit=1&last-updated-datetime__gt=2017-08-12`:

![screen shot 2017-08-14 at 17 06 42](https://user-images.githubusercontent.com/23729009/29280397-fd380714-8112-11e7-9e81-4918975e4ff9.png)

**Comment by andylolz** [comment]
That’s due to a bug with the source IATI data for Belgian Development Agency (BTC). See:
https://open.btcctb.org/iati/all-activities.xml

![screen shot 2017-08-17 at 10 28 38](https://user-images.githubusercontent.com/464193/29405817-f6367dc6-8336-11e7-91cb-a92bc8c65e9a.png)

**Comment by allthatilk** [comment]
Great sleuthing! This does seem to be the case, though I believe I did find this problem with more than one dataset last week but now can't replicate this. Will close and hopefully this won't crop up again in the future =)
