### ISSUE TITLE
Every page responds with a 500 error

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Datastore#289]
Par exemple:
http://datastore.iatistandard.org/api/1/about

This was originally reported by @jabbamon here: IATI/IATI-Query-Builder#104

**Comment by hayfield** [comment]
I have rebooted the server and it is now returning data rather than an error.

**Comment by andylolz** [comment]
Great – thanks!

Any idea what the cause of the problem was?

**Comment by hayfield** [comment]
Looking into the matter, there don't appear to have been any relevant log files set up when the Datastore was made, so unfortunately not. :(

I will create an issue to note that this is an issue.
