### ISSUE TITLE
CORS (and JSONP?) support

### ISSUE THREAD

**Issue by rufuspollock** [IATI/IATI-Datastore#34]
Lots of example e.g. in pybossa of how to do this ...

See e.g.

jsonp / jsonify: https://github.com/PyBossa/pybossa/blob/master/pybossa/util.py#L29

CORS: https://github.com/PyBossa/pybossa/blob/master/pybossa/util.py#L54

**Comment by Bjwebb** [comment]
I've added CORS support to the live datastore by setting the appropriate header in the Apache config (` Header set Access-Control-Allow-Origin "*"`).

Leaving this issue open as we may want to set the header in the application instead, or we may still want to support JSONP.
