### ISSUE TITLE
DataError API: Dirty data  is not necessarily failed data

### ISSUE THREAD

**Issue by caprenter** [IATI/iati-datastore#90]
I think with activity_importer errors, there may be cases where data is being rejected when it should be included.

I'm not sure on the agreement with this, but generally, I think this is around values that are not on current IATI codelists.
Sectors is a good example - publishers often use code values that may not be on the current IATI sector list:
http://iatistandard.org/codelists/sector/

Generally, these values should be included, even if they do not conform to the list. This is 'dirty data', but should not fail.

Similarly, a commonly used country code is XK for Kosovo, but this is not as yet on our codelist, but should be allowed into the datastore.
http://iatistandard.org/codelists/country/

This may need more clarification, so please ask.

**Comment by Bjwebb** [comment]
This has been fixed whilst implementing 2.01 support, on the support-iatistandard-2.01 branch, which will be merged in a couple of weeks.
